site_name: Nexar
site_url: https://bexli.dev/nexar
repo_url: https://github.com/joshpaulie/nexar
repo_name: joshpaulie/nexar
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    # Palette toggle for dark mode
    - scheme: slate
  icon:
    repo: fontawesome/brands/github
  features:
    - content.code.annotate # Allow code annotations
    - content.code.copy # Copy code blocks to clipboard
    - content.action.edit # Edit button for pages
    - content.action.view # View button for pages
    - navigation.instant # Make mkdocs act as a single-page app
    - navigation.instant.prefetch # Load hovered pages in the background
    - navigation.instant.progress # Loading bar for instant navigation
    - navigation.instant.preview # Show a preview of the page when hovering links
    - navigation.tracking # Add anchor to url when clicking a section
    - navigation.sections # Expand all selections in side navbar
    - navigation.path # Breadcrumbs along top
    - navigation.top # Back to top button
    - navigation.indexes

nav:
  - Home:
      - Home: index.md
      - Quick Start: quick_start.md
  - Features:
      - Caching: client-features/caching.md
      - Rate limiting: client-features/rate-limiting.md
      - Debugging API Responses: client-features/debug-responses.md
  - Examples:
      - Batch Players: examples/batch_players.md
      - Sort Players by Rank: examples/soft_players_by_rank.md
      - Match history:
          - Match History: examples/match_history.md
          - Player Performance: examples/player_performance.md
          - Champion Performance: examples/champ_performance.md
  - Reference:
      - Client: reference/client.md
      - Models:
          - Player: reference/models/player.md
          - Match: reference/models/match.md
          - ParticipantList: reference/models/participant-list.md
  - FAQ: FAQ.md
  - Why not Nexar?: why-not-nexar.md

markdown_extensions:
  # "Admonitions" (Callouts)
  - admonition
  - pymdownx.details
  - pymdownx.superfences

  # "PymdownX extensions"
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: docs/snippets
      dedent_subsections: true
  # Tabbed sections
  - pymdownx.tabbed:
      alternate_style: true

  # Tooltips
  - abbr
  - attr_list

  # Annotations
  - attr_list
  - md_in_html

  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  - mkdocstrings
