[project]
name = "nexar"
version = "0.1.0"
description = "A simple, Pythonic SDK for Riot's League of Legends API"
readme = "README.md"
authors = [
    { name = "bex", email = "30572280+JoshPaulie@users.noreply.github.com" },
]
requires-python = ">=3.13"
dependencies = ["requests>=2.32.4"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F", "I", "N", "UP"]
ignore = []

[dependency-groups]
dev = [
    "pytest>=8.4.1",
    "requests-mock>=1.12.1",
]
